version: '3.3'

networks:
  main:

services:
  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    ports:
        - '3000:3000'

  flagtool:
    image: ${DOCKER_USERNAME}/flag-tool
    container_name: flag-tool
    networks:
      - main
    command: tail -f /dev/null